/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as PBoardSlugRouteImport } from './routes/p.$boardSlug'
import { Route as AppSSpaceIdRouteRouteImport } from './routes/_app/s.$spaceId/route'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAiRouteImport } from './routes/_app/settings/ai'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app/settings/appearance'
import { Route as AppSettingsCollaborationRouteImport } from './routes/_app/settings/collaboration'
import { Route as AppSettingsEditorRouteImport } from './routes/_app/settings/editor'
import { Route as AppSettingsInterfaceRouteImport } from './routes/_app/settings/interface'
import { Route as AppSettingsLinksRouteImport } from './routes/_app/settings/links'
import { Route as AppSettingsPrivacyRouteImport } from './routes/_app/settings/privacy'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'
import { Route as AppSettingsSearchRouteImport } from './routes/_app/settings/search'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app/settings/security'
import { Route as AppSettingsShortcutsRouteImport } from './routes/_app/settings/shortcuts'
import { Route as AppSSpaceIdIndexRouteImport } from './routes/_app/s.$spaceId/index'
import { Route as AppSSpaceIdDbDatabaseIdRouteImport } from './routes/_app/s.$spaceId/db.$databaseId'
import { Route as AppSSpaceIdPPageIdRouteImport } from './routes/_app/s.$spaceId/p.$pageId'
import { Route as AppSSpaceIdProjectsIndexRouteImport } from './routes/_app/s.$spaceId/projects/index'
import { Route as AppSSpaceIdProjectsBoardIdRouteImport } from './routes/_app/s.$spaceId/projects/$boardId'
import { Route as AppSSpaceIdSettingsMembersRouteImport } from './routes/_app/s.$spaceId/settings/members'
import { Route as AppSSpaceIdProjectsBoardIdIndexRouteImport } from './routes/_app/s.$spaceId/projects/$boardId/index'
import { Route as AppSSpaceIdProjectsBoardIdSettingsRouteRouteImport } from './routes/_app/s.$spaceId/projects/$boardId/settings/route'
import { Route as AppSSpaceIdProjectsBoardIdSettingsIndexRouteImport } from './routes/_app/s.$spaceId/projects/$boardId/settings/index'
import { Route as AppSSpaceIdProjectsBoardIdSettingsLabelsRouteImport } from './routes/_app/s.$spaceId/projects/$boardId/settings/labels'
import { Route as AppSSpaceIdProjectsBoardIdSettingsMilestonesRouteImport } from './routes/_app/s.$spaceId/projects/$boardId/settings/milestones'
import { Route as AppSSpaceIdProjectsBoardIdSettingsPublicRouteImport } from './routes/_app/s.$spaceId/projects/$boardId/settings/public'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PBoardSlugRoute = PBoardSlugRouteImport.update({
  id: '/p/$boardSlug',
  path: '/p/$boardSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSSpaceIdRouteRoute = AppSSpaceIdRouteRouteImport.update({
  id: '/s/$spaceId',
  path: '/s/$spaceId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAiRoute = AppSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsCollaborationRoute =
  AppSettingsCollaborationRouteImport.update({
    id: '/collaboration',
    path: '/collaboration',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsEditorRoute = AppSettingsEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsInterfaceRoute = AppSettingsInterfaceRouteImport.update({
  id: '/interface',
  path: '/interface',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsLinksRoute = AppSettingsLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsPrivacyRoute = AppSettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsSearchRoute = AppSettingsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsShortcutsRoute = AppSettingsShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSSpaceIdIndexRoute = AppSSpaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSSpaceIdRouteRoute,
} as any)
const AppSSpaceIdDbDatabaseIdRoute = AppSSpaceIdDbDatabaseIdRouteImport.update({
  id: '/db/$databaseId',
  path: '/db/$databaseId',
  getParentRoute: () => AppSSpaceIdRouteRoute,
} as any)
const AppSSpaceIdPPageIdRoute = AppSSpaceIdPPageIdRouteImport.update({
  id: '/p/$pageId',
  path: '/p/$pageId',
  getParentRoute: () => AppSSpaceIdRouteRoute,
} as any)
const AppSSpaceIdProjectsIndexRoute =
  AppSSpaceIdProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AppSSpaceIdRouteRoute,
  } as any)
const AppSSpaceIdProjectsBoardIdRoute =
  AppSSpaceIdProjectsBoardIdRouteImport.update({
    id: '/projects/$boardId',
    path: '/projects/$boardId',
    getParentRoute: () => AppSSpaceIdRouteRoute,
  } as any)
const AppSSpaceIdSettingsMembersRoute =
  AppSSpaceIdSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => AppSSpaceIdRouteRoute,
  } as any)
const AppSSpaceIdProjectsBoardIdIndexRoute =
  AppSSpaceIdProjectsBoardIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppSSpaceIdProjectsBoardIdRoute,
  } as any)
const AppSSpaceIdProjectsBoardIdSettingsRouteRoute =
  AppSSpaceIdProjectsBoardIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppSSpaceIdProjectsBoardIdRoute,
  } as any)
const AppSSpaceIdProjectsBoardIdSettingsIndexRoute =
  AppSSpaceIdProjectsBoardIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppSSpaceIdProjectsBoardIdSettingsRouteRoute,
  } as any)
const AppSSpaceIdProjectsBoardIdSettingsLabelsRoute =
  AppSSpaceIdProjectsBoardIdSettingsLabelsRouteImport.update({
    id: '/labels',
    path: '/labels',
    getParentRoute: () => AppSSpaceIdProjectsBoardIdSettingsRouteRoute,
  } as any)
const AppSSpaceIdProjectsBoardIdSettingsMilestonesRoute =
  AppSSpaceIdProjectsBoardIdSettingsMilestonesRouteImport.update({
    id: '/milestones',
    path: '/milestones',
    getParentRoute: () => AppSSpaceIdProjectsBoardIdSettingsRouteRoute,
  } as any)
const AppSSpaceIdProjectsBoardIdSettingsPublicRoute =
  AppSSpaceIdProjectsBoardIdSettingsPublicRouteImport.update({
    id: '/public',
    path: '/public',
    getParentRoute: () => AppSSpaceIdProjectsBoardIdSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/p/$boardSlug': typeof PBoardSlugRoute
  '/s/$spaceId': typeof AppSSpaceIdRouteRouteWithChildren
  '/settings/ai': typeof AppSettingsAiRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/collaboration': typeof AppSettingsCollaborationRoute
  '/settings/editor': typeof AppSettingsEditorRoute
  '/settings/interface': typeof AppSettingsInterfaceRoute
  '/settings/links': typeof AppSettingsLinksRoute
  '/settings/privacy': typeof AppSettingsPrivacyRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/search': typeof AppSettingsSearchRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/shortcuts': typeof AppSettingsShortcutsRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/s/$spaceId/': typeof AppSSpaceIdIndexRoute
  '/s/$spaceId/db/$databaseId': typeof AppSSpaceIdDbDatabaseIdRoute
  '/s/$spaceId/p/$pageId': typeof AppSSpaceIdPPageIdRoute
  '/s/$spaceId/projects/$boardId': typeof AppSSpaceIdProjectsBoardIdRouteWithChildren
  '/s/$spaceId/settings/members': typeof AppSSpaceIdSettingsMembersRoute
  '/s/$spaceId/projects/': typeof AppSSpaceIdProjectsIndexRoute
  '/s/$spaceId/projects/$boardId/settings': typeof AppSSpaceIdProjectsBoardIdSettingsRouteRouteWithChildren
  '/s/$spaceId/projects/$boardId/': typeof AppSSpaceIdProjectsBoardIdIndexRoute
  '/s/$spaceId/projects/$boardId/settings/labels': typeof AppSSpaceIdProjectsBoardIdSettingsLabelsRoute
  '/s/$spaceId/projects/$boardId/settings/milestones': typeof AppSSpaceIdProjectsBoardIdSettingsMilestonesRoute
  '/s/$spaceId/projects/$boardId/settings/public': typeof AppSSpaceIdProjectsBoardIdSettingsPublicRoute
  '/s/$spaceId/projects/$boardId/settings/': typeof AppSSpaceIdProjectsBoardIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$boardSlug': typeof PBoardSlugRoute
  '/': typeof AppIndexRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/collaboration': typeof AppSettingsCollaborationRoute
  '/settings/editor': typeof AppSettingsEditorRoute
  '/settings/interface': typeof AppSettingsInterfaceRoute
  '/settings/links': typeof AppSettingsLinksRoute
  '/settings/privacy': typeof AppSettingsPrivacyRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/search': typeof AppSettingsSearchRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/shortcuts': typeof AppSettingsShortcutsRoute
  '/settings': typeof AppSettingsIndexRoute
  '/s/$spaceId': typeof AppSSpaceIdIndexRoute
  '/s/$spaceId/db/$databaseId': typeof AppSSpaceIdDbDatabaseIdRoute
  '/s/$spaceId/p/$pageId': typeof AppSSpaceIdPPageIdRoute
  '/s/$spaceId/settings/members': typeof AppSSpaceIdSettingsMembersRoute
  '/s/$spaceId/projects': typeof AppSSpaceIdProjectsIndexRoute
  '/s/$spaceId/projects/$boardId': typeof AppSSpaceIdProjectsBoardIdIndexRoute
  '/s/$spaceId/projects/$boardId/settings/labels': typeof AppSSpaceIdProjectsBoardIdSettingsLabelsRoute
  '/s/$spaceId/projects/$boardId/settings/milestones': typeof AppSSpaceIdProjectsBoardIdSettingsMilestonesRoute
  '/s/$spaceId/projects/$boardId/settings/public': typeof AppSSpaceIdProjectsBoardIdSettingsPublicRoute
  '/s/$spaceId/projects/$boardId/settings': typeof AppSSpaceIdProjectsBoardIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/p/$boardSlug': typeof PBoardSlugRoute
  '/_app/': typeof AppIndexRoute
  '/_app/s/$spaceId': typeof AppSSpaceIdRouteRouteWithChildren
  '/_app/settings/ai': typeof AppSettingsAiRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/collaboration': typeof AppSettingsCollaborationRoute
  '/_app/settings/editor': typeof AppSettingsEditorRoute
  '/_app/settings/interface': typeof AppSettingsInterfaceRoute
  '/_app/settings/links': typeof AppSettingsLinksRoute
  '/_app/settings/privacy': typeof AppSettingsPrivacyRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/search': typeof AppSettingsSearchRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/settings/shortcuts': typeof AppSettingsShortcutsRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/s/$spaceId/': typeof AppSSpaceIdIndexRoute
  '/_app/s/$spaceId/db/$databaseId': typeof AppSSpaceIdDbDatabaseIdRoute
  '/_app/s/$spaceId/p/$pageId': typeof AppSSpaceIdPPageIdRoute
  '/_app/s/$spaceId/projects/$boardId': typeof AppSSpaceIdProjectsBoardIdRouteWithChildren
  '/_app/s/$spaceId/settings/members': typeof AppSSpaceIdSettingsMembersRoute
  '/_app/s/$spaceId/projects/': typeof AppSSpaceIdProjectsIndexRoute
  '/_app/s/$spaceId/projects/$boardId/settings': typeof AppSSpaceIdProjectsBoardIdSettingsRouteRouteWithChildren
  '/_app/s/$spaceId/projects/$boardId/': typeof AppSSpaceIdProjectsBoardIdIndexRoute
  '/_app/s/$spaceId/projects/$boardId/settings/labels': typeof AppSSpaceIdProjectsBoardIdSettingsLabelsRoute
  '/_app/s/$spaceId/projects/$boardId/settings/milestones': typeof AppSSpaceIdProjectsBoardIdSettingsMilestonesRoute
  '/_app/s/$spaceId/projects/$boardId/settings/public': typeof AppSSpaceIdProjectsBoardIdSettingsPublicRoute
  '/_app/s/$spaceId/projects/$boardId/settings/': typeof AppSSpaceIdProjectsBoardIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/invite/$token'
    | '/p/$boardSlug'
    | '/s/$spaceId'
    | '/settings/ai'
    | '/settings/appearance'
    | '/settings/collaboration'
    | '/settings/editor'
    | '/settings/interface'
    | '/settings/links'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/search'
    | '/settings/security'
    | '/settings/shortcuts'
    | '/settings/'
    | '/s/$spaceId/'
    | '/s/$spaceId/db/$databaseId'
    | '/s/$spaceId/p/$pageId'
    | '/s/$spaceId/projects/$boardId'
    | '/s/$spaceId/settings/members'
    | '/s/$spaceId/projects/'
    | '/s/$spaceId/projects/$boardId/settings'
    | '/s/$spaceId/projects/$boardId/'
    | '/s/$spaceId/projects/$boardId/settings/labels'
    | '/s/$spaceId/projects/$boardId/settings/milestones'
    | '/s/$spaceId/projects/$boardId/settings/public'
    | '/s/$spaceId/projects/$boardId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/invite/$token'
    | '/p/$boardSlug'
    | '/'
    | '/settings/ai'
    | '/settings/appearance'
    | '/settings/collaboration'
    | '/settings/editor'
    | '/settings/interface'
    | '/settings/links'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/search'
    | '/settings/security'
    | '/settings/shortcuts'
    | '/settings'
    | '/s/$spaceId'
    | '/s/$spaceId/db/$databaseId'
    | '/s/$spaceId/p/$pageId'
    | '/s/$spaceId/settings/members'
    | '/s/$spaceId/projects'
    | '/s/$spaceId/projects/$boardId'
    | '/s/$spaceId/projects/$boardId/settings/labels'
    | '/s/$spaceId/projects/$boardId/settings/milestones'
    | '/s/$spaceId/projects/$boardId/settings/public'
    | '/s/$spaceId/projects/$boardId/settings'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/settings'
    | '/invite/$token'
    | '/p/$boardSlug'
    | '/_app/'
    | '/_app/s/$spaceId'
    | '/_app/settings/ai'
    | '/_app/settings/appearance'
    | '/_app/settings/collaboration'
    | '/_app/settings/editor'
    | '/_app/settings/interface'
    | '/_app/settings/links'
    | '/_app/settings/privacy'
    | '/_app/settings/profile'
    | '/_app/settings/search'
    | '/_app/settings/security'
    | '/_app/settings/shortcuts'
    | '/_app/settings/'
    | '/_app/s/$spaceId/'
    | '/_app/s/$spaceId/db/$databaseId'
    | '/_app/s/$spaceId/p/$pageId'
    | '/_app/s/$spaceId/projects/$boardId'
    | '/_app/s/$spaceId/settings/members'
    | '/_app/s/$spaceId/projects/'
    | '/_app/s/$spaceId/projects/$boardId/settings'
    | '/_app/s/$spaceId/projects/$boardId/'
    | '/_app/s/$spaceId/projects/$boardId/settings/labels'
    | '/_app/s/$spaceId/projects/$boardId/settings/milestones'
    | '/_app/s/$spaceId/projects/$boardId/settings/public'
    | '/_app/s/$spaceId/projects/$boardId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PBoardSlugRoute: typeof PBoardSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$boardSlug': {
      id: '/p/$boardSlug'
      path: '/p/$boardSlug'
      fullPath: '/p/$boardSlug'
      preLoaderRoute: typeof PBoardSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/s/$spaceId': {
      id: '/_app/s/$spaceId'
      path: '/s/$spaceId'
      fullPath: '/s/$spaceId'
      preLoaderRoute: typeof AppSSpaceIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/ai': {
      id: '/_app/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AppSettingsAiRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/collaboration': {
      id: '/_app/settings/collaboration'
      path: '/collaboration'
      fullPath: '/settings/collaboration'
      preLoaderRoute: typeof AppSettingsCollaborationRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/editor': {
      id: '/_app/settings/editor'
      path: '/editor'
      fullPath: '/settings/editor'
      preLoaderRoute: typeof AppSettingsEditorRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/interface': {
      id: '/_app/settings/interface'
      path: '/interface'
      fullPath: '/settings/interface'
      preLoaderRoute: typeof AppSettingsInterfaceRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/links': {
      id: '/_app/settings/links'
      path: '/links'
      fullPath: '/settings/links'
      preLoaderRoute: typeof AppSettingsLinksRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/privacy': {
      id: '/_app/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AppSettingsPrivacyRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/search': {
      id: '/_app/settings/search'
      path: '/search'
      fullPath: '/settings/search'
      preLoaderRoute: typeof AppSettingsSearchRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/shortcuts': {
      id: '/_app/settings/shortcuts'
      path: '/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof AppSettingsShortcutsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/s/$spaceId/': {
      id: '/_app/s/$spaceId/'
      path: '/'
      fullPath: '/s/$spaceId/'
      preLoaderRoute: typeof AppSSpaceIdIndexRouteImport
      parentRoute: typeof AppSSpaceIdRouteRoute
    }
    '/_app/s/$spaceId/db/$databaseId': {
      id: '/_app/s/$spaceId/db/$databaseId'
      path: '/db/$databaseId'
      fullPath: '/s/$spaceId/db/$databaseId'
      preLoaderRoute: typeof AppSSpaceIdDbDatabaseIdRouteImport
      parentRoute: typeof AppSSpaceIdRouteRoute
    }
    '/_app/s/$spaceId/p/$pageId': {
      id: '/_app/s/$spaceId/p/$pageId'
      path: '/p/$pageId'
      fullPath: '/s/$spaceId/p/$pageId'
      preLoaderRoute: typeof AppSSpaceIdPPageIdRouteImport
      parentRoute: typeof AppSSpaceIdRouteRoute
    }
    '/_app/s/$spaceId/projects/': {
      id: '/_app/s/$spaceId/projects/'
      path: '/projects'
      fullPath: '/s/$spaceId/projects/'
      preLoaderRoute: typeof AppSSpaceIdProjectsIndexRouteImport
      parentRoute: typeof AppSSpaceIdRouteRoute
    }
    '/_app/s/$spaceId/projects/$boardId': {
      id: '/_app/s/$spaceId/projects/$boardId'
      path: '/projects/$boardId'
      fullPath: '/s/$spaceId/projects/$boardId'
      preLoaderRoute: typeof AppSSpaceIdProjectsBoardIdRouteImport
      parentRoute: typeof AppSSpaceIdRouteRoute
    }
    '/_app/s/$spaceId/settings/members': {
      id: '/_app/s/$spaceId/settings/members'
      path: '/settings/members'
      fullPath: '/s/$spaceId/settings/members'
      preLoaderRoute: typeof AppSSpaceIdSettingsMembersRouteImport
      parentRoute: typeof AppSSpaceIdRouteRoute
    }
    '/_app/s/$spaceId/projects/$boardId/': {
      id: '/_app/s/$spaceId/projects/$boardId/'
      path: '/'
      fullPath: '/s/$spaceId/projects/$boardId/'
      preLoaderRoute: typeof AppSSpaceIdProjectsBoardIdIndexRouteImport
      parentRoute: typeof AppSSpaceIdProjectsBoardIdRoute
    }
    '/_app/s/$spaceId/projects/$boardId/settings': {
      id: '/_app/s/$spaceId/projects/$boardId/settings'
      path: '/settings'
      fullPath: '/s/$spaceId/projects/$boardId/settings'
      preLoaderRoute: typeof AppSSpaceIdProjectsBoardIdSettingsRouteRouteImport
      parentRoute: typeof AppSSpaceIdProjectsBoardIdRoute
    }
    '/_app/s/$spaceId/projects/$boardId/settings/': {
      id: '/_app/s/$spaceId/projects/$boardId/settings/'
      path: '/'
      fullPath: '/s/$spaceId/projects/$boardId/settings/'
      preLoaderRoute: typeof AppSSpaceIdProjectsBoardIdSettingsIndexRouteImport
      parentRoute: typeof AppSSpaceIdProjectsBoardIdSettingsRouteRoute
    }
    '/_app/s/$spaceId/projects/$boardId/settings/labels': {
      id: '/_app/s/$spaceId/projects/$boardId/settings/labels'
      path: '/labels'
      fullPath: '/s/$spaceId/projects/$boardId/settings/labels'
      preLoaderRoute: typeof AppSSpaceIdProjectsBoardIdSettingsLabelsRouteImport
      parentRoute: typeof AppSSpaceIdProjectsBoardIdSettingsRouteRoute
    }
    '/_app/s/$spaceId/projects/$boardId/settings/milestones': {
      id: '/_app/s/$spaceId/projects/$boardId/settings/milestones'
      path: '/milestones'
      fullPath: '/s/$spaceId/projects/$boardId/settings/milestones'
      preLoaderRoute: typeof AppSSpaceIdProjectsBoardIdSettingsMilestonesRouteImport
      parentRoute: typeof AppSSpaceIdProjectsBoardIdSettingsRouteRoute
    }
    '/_app/s/$spaceId/projects/$boardId/settings/public': {
      id: '/_app/s/$spaceId/projects/$boardId/settings/public'
      path: '/public'
      fullPath: '/s/$spaceId/projects/$boardId/settings/public'
      preLoaderRoute: typeof AppSSpaceIdProjectsBoardIdSettingsPublicRouteImport
      parentRoute: typeof AppSSpaceIdProjectsBoardIdSettingsRouteRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsAiRoute: typeof AppSettingsAiRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsCollaborationRoute: typeof AppSettingsCollaborationRoute
  AppSettingsEditorRoute: typeof AppSettingsEditorRoute
  AppSettingsInterfaceRoute: typeof AppSettingsInterfaceRoute
  AppSettingsLinksRoute: typeof AppSettingsLinksRoute
  AppSettingsPrivacyRoute: typeof AppSettingsPrivacyRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSearchRoute: typeof AppSettingsSearchRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsShortcutsRoute: typeof AppSettingsShortcutsRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAiRoute: AppSettingsAiRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsCollaborationRoute: AppSettingsCollaborationRoute,
  AppSettingsEditorRoute: AppSettingsEditorRoute,
  AppSettingsInterfaceRoute: AppSettingsInterfaceRoute,
  AppSettingsLinksRoute: AppSettingsLinksRoute,
  AppSettingsPrivacyRoute: AppSettingsPrivacyRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSearchRoute: AppSettingsSearchRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsShortcutsRoute: AppSettingsShortcutsRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppSSpaceIdProjectsBoardIdSettingsRouteRouteChildren {
  AppSSpaceIdProjectsBoardIdSettingsLabelsRoute: typeof AppSSpaceIdProjectsBoardIdSettingsLabelsRoute
  AppSSpaceIdProjectsBoardIdSettingsMilestonesRoute: typeof AppSSpaceIdProjectsBoardIdSettingsMilestonesRoute
  AppSSpaceIdProjectsBoardIdSettingsPublicRoute: typeof AppSSpaceIdProjectsBoardIdSettingsPublicRoute
  AppSSpaceIdProjectsBoardIdSettingsIndexRoute: typeof AppSSpaceIdProjectsBoardIdSettingsIndexRoute
}

const AppSSpaceIdProjectsBoardIdSettingsRouteRouteChildren: AppSSpaceIdProjectsBoardIdSettingsRouteRouteChildren =
  {
    AppSSpaceIdProjectsBoardIdSettingsLabelsRoute:
      AppSSpaceIdProjectsBoardIdSettingsLabelsRoute,
    AppSSpaceIdProjectsBoardIdSettingsMilestonesRoute:
      AppSSpaceIdProjectsBoardIdSettingsMilestonesRoute,
    AppSSpaceIdProjectsBoardIdSettingsPublicRoute:
      AppSSpaceIdProjectsBoardIdSettingsPublicRoute,
    AppSSpaceIdProjectsBoardIdSettingsIndexRoute:
      AppSSpaceIdProjectsBoardIdSettingsIndexRoute,
  }

const AppSSpaceIdProjectsBoardIdSettingsRouteRouteWithChildren =
  AppSSpaceIdProjectsBoardIdSettingsRouteRoute._addFileChildren(
    AppSSpaceIdProjectsBoardIdSettingsRouteRouteChildren,
  )

interface AppSSpaceIdProjectsBoardIdRouteChildren {
  AppSSpaceIdProjectsBoardIdSettingsRouteRoute: typeof AppSSpaceIdProjectsBoardIdSettingsRouteRouteWithChildren
  AppSSpaceIdProjectsBoardIdIndexRoute: typeof AppSSpaceIdProjectsBoardIdIndexRoute
}

const AppSSpaceIdProjectsBoardIdRouteChildren: AppSSpaceIdProjectsBoardIdRouteChildren =
  {
    AppSSpaceIdProjectsBoardIdSettingsRouteRoute:
      AppSSpaceIdProjectsBoardIdSettingsRouteRouteWithChildren,
    AppSSpaceIdProjectsBoardIdIndexRoute: AppSSpaceIdProjectsBoardIdIndexRoute,
  }

const AppSSpaceIdProjectsBoardIdRouteWithChildren =
  AppSSpaceIdProjectsBoardIdRoute._addFileChildren(
    AppSSpaceIdProjectsBoardIdRouteChildren,
  )

interface AppSSpaceIdRouteRouteChildren {
  AppSSpaceIdIndexRoute: typeof AppSSpaceIdIndexRoute
  AppSSpaceIdDbDatabaseIdRoute: typeof AppSSpaceIdDbDatabaseIdRoute
  AppSSpaceIdPPageIdRoute: typeof AppSSpaceIdPPageIdRoute
  AppSSpaceIdProjectsBoardIdRoute: typeof AppSSpaceIdProjectsBoardIdRouteWithChildren
  AppSSpaceIdSettingsMembersRoute: typeof AppSSpaceIdSettingsMembersRoute
  AppSSpaceIdProjectsIndexRoute: typeof AppSSpaceIdProjectsIndexRoute
}

const AppSSpaceIdRouteRouteChildren: AppSSpaceIdRouteRouteChildren = {
  AppSSpaceIdIndexRoute: AppSSpaceIdIndexRoute,
  AppSSpaceIdDbDatabaseIdRoute: AppSSpaceIdDbDatabaseIdRoute,
  AppSSpaceIdPPageIdRoute: AppSSpaceIdPPageIdRoute,
  AppSSpaceIdProjectsBoardIdRoute: AppSSpaceIdProjectsBoardIdRouteWithChildren,
  AppSSpaceIdSettingsMembersRoute: AppSSpaceIdSettingsMembersRoute,
  AppSSpaceIdProjectsIndexRoute: AppSSpaceIdProjectsIndexRoute,
}

const AppSSpaceIdRouteRouteWithChildren =
  AppSSpaceIdRouteRoute._addFileChildren(AppSSpaceIdRouteRouteChildren)

interface AppRouteRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppSSpaceIdRouteRoute: typeof AppSSpaceIdRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppSSpaceIdRouteRoute: AppSSpaceIdRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  InviteTokenRoute: InviteTokenRoute,
  PBoardSlugRoute: PBoardSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
